<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Viernes</AssemblyName>
    <RootNamespace>Viernes.App</RootNamespace>
    <ApplicationIcon Condition="Exists('Assets\Viernes.ico')">Assets\Viernes.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viernes.Core\Viernes.Core.csproj" />
    <ProjectReference Include="..\Viernes.Memory\Viernes.Memory.csproj" />
    <ProjectReference Include="..\Viernes.Platform.Windows\Viernes.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
