namespace Viernes.Core.Configuration;

using System.Globalization;
using Viernes.Core.Usage;

/// <summary>
/// Runtime configuration for the provider-neutral core. The API key is read only from
/// <c>OPENROUTER_API_KEY</c>. Fast selection uses <c>VIERNES_OPENROUTER_FAST_MODEL</c> and
/// comma-separated alternatives use <c>VIERNES_OPENROUTER_FAST_FALLBACK_MODELS</c>; legacy names
/// without <c>FAST</c> remain compatible. Explicit lanes use
/// <c>VIERNES_OPENROUTER_AGENT_MODEL</c>, <c>VIERNES_OPENROUTER_REASONING_MODEL</c>, and the optional
/// <c>VIERNES_OPENROUTER_PREMIUM_MODEL</c>. The legacy <c>VIERNES_OPENROUTER_PLANNING_MODEL</c> remains
/// an Agent alias. Global guardrails use <c>VIERNES_OPENROUTER_DAILY_BUDGET_USD</c>,
/// <c>VIERNES_OPENROUTER_MONTHLY_BUDGET_USD</c>, <c>VIERNES_OPENROUTER_MAX_REQUESTS_PER_DAY</c>, and
/// <c>VIERNES_MAX_DEEP_TASKS_PER_DAY</c>. Per-role variables are generated by the public
/// <c>GetRole*EnvironmentVariable</c> helpers. Prices are provided at runtime through
/// <c>VIERNES_OPENROUTER_RATES_JSON</c>; no mutable provider price is compiled in.
/// </summary>
public sealed class ViernesOptions
{
    public const string ApiKeyEnvironmentVariable = "OPENROUTER_API_KEY";
    public const string FastModelEnvironmentVariable = "VIERNES_OPENROUTER_FAST_MODEL";
    public const string FastFallbackModelsEnvironmentVariable = "VIERNES_OPENROUTER_FAST_FALLBACK_MODELS";
    /// <summary>Legacy fast-model variable retained for compatibility.</summary>
    public const string ModelEnvironmentVariable = "VIERNES_OPENROUTER_MODEL";
    /// <summary>Legacy fast-fallback variable retained for compatibility.</summary>
    public const string FallbackModelsEnvironmentVariable = "VIERNES_OPENROUTER_FALLBACK_MODELS";
    public const string AgentModelEnvironmentVariable = "VIERNES_OPENROUTER_AGENT_MODEL";
    public const string ReasoningModelEnvironmentVariable = "VIERNES_OPENROUTER_REASONING_MODEL";
    public const string PremiumModelEnvironmentVariable = "VIERNES_OPENROUTER_PREMIUM_MODEL";
    public const string EmbeddingsModelEnvironmentVariable = "VIERNES_OPENROUTER_EMBEDDINGS_MODEL";
    public const string LocalSummaryModelEnvironmentVariable = "VIERNES_OPENROUTER_LOCAL_SUMMARY_MODEL";
    public const string PreferLocalEmbeddingsEnvironmentVariable = "VIERNES_PREFER_LOCAL_EMBEDDINGS";
    public const string PreferLocalSummaryEnvironmentVariable = "VIERNES_PREFER_LOCAL_SUMMARY";
    public const string PlanningModelEnvironmentVariable = "VIERNES_OPENROUTER_PLANNING_MODEL";
    public const string DailyBudgetEnvironmentVariable = "VIERNES_OPENROUTER_DAILY_BUDGET_USD";
    public const string MonthlyBudgetEnvironmentVariable = "VIERNES_OPENROUTER_MONTHLY_BUDGET_USD";
    public const string MaxRequestsEnvironmentVariable = "VIERNES_OPENROUTER_MAX_REQUESTS_PER_DAY";
    public const string MaxDeepTasksEnvironmentVariable = "VIERNES_MAX_DEEP_TASKS_PER_DAY";
    public const string RateCardEnvironmentVariable = "VIERNES_OPENROUTER_RATES_JSON";

    public const string DefaultModel = "openai/gpt-5.6-luna";
    public const string DefaultAgentModel = "openai/gpt-5.6-terra";
    public const string DefaultPlanningModel = DefaultAgentModel;
    public const string DefaultReasoningModel = "~anthropic/claude-sonnet-latest";

    private static readonly string[] DefaultFallbackModelsValue =
    [
        "~google/gemini-flash-latest"
    ];

    private readonly string? _apiKey;
    private readonly IReadOnlyList<string> _fallbackModels;

    public ViernesOptions(
        string? apiKey = null,
        string? model = null,
        IEnumerable<string>? fallbackModels = null,
        Uri? openRouterEndpoint = null,
        string applicationName = "Viernes",
        int maxToolIterations = 3,
        string? planningModel = null,
        decimal? dailyBudgetUsd = null,
        decimal? monthlyBudgetUsd = null,
        int maxDeepTasksPerDay = 3,
        string? agentModel = null,
        string? reasoningModel = null,
        string? premiumModel = null,
        string? embeddingsModel = null,
        string? localSummaryModel = null,
        bool preferLocalEmbeddings = true,
        bool preferLocalSummary = true,
        int? maxRequestsPerDay = null,
        IEnumerable<RoleBudgetLimits>? roleBudgetLimits = null,
        UsageRateCard? usageRateCard = null)
    {
        _apiKey = NormalizeSecret(apiKey);
        Model = NormalizeModel(model) ?? DefaultModel;
        _fallbackModels = NormalizeFallbacks(fallbackModels, Model);
        OpenRouterEndpoint = ValidateEndpoint(openRouterEndpoint ??
            new Uri("https://openrouter.ai/api/v1/chat/completions", UriKind.Absolute));
        ApplicationName = string.IsNullOrWhiteSpace(applicationName) ? "Viernes" : applicationName.Trim();
        AgentModel = NormalizeModel(agentModel) ?? NormalizeModel(planningModel) ?? DefaultAgentModel;
        PlanningModel = AgentModel;
        ReasoningModel = NormalizeModel(reasoningModel) ?? DefaultReasoningModel;
        PremiumModel = NormalizeModel(premiumModel);
        EmbeddingsModel = NormalizeModel(embeddingsModel);
        LocalSummaryModel = NormalizeModel(localSummaryModel);
        PreferLocalEmbeddings = preferLocalEmbeddings;
        PreferLocalSummary = preferLocalSummary;
        DailyBudgetUsd = ValidateBudget(dailyBudgetUsd, nameof(dailyBudgetUsd));
        MonthlyBudgetUsd = ValidateBudget(monthlyBudgetUsd, nameof(monthlyBudgetUsd));
        MaxDeepTasksPerDay = maxDeepTasksPerDay is >= 0 and <= 100
            ? maxDeepTasksPerDay
            : throw new ArgumentOutOfRangeException(
                nameof(maxDeepTasksPerDay),
                "Use between 0 and 100 deep tasks per day.");
        MaxToolIterations = maxToolIterations is >= 1 and <= 8
            ? maxToolIterations
            : throw new ArgumentOutOfRangeException(nameof(maxToolIterations), "Use between 1 and 8 tool iterations.");
        Portfolio = new ModelPortfolio(
            Model,
            _fallbackModels,
            AgentModel,
            ReasoningModel,
            PremiumModel,
            EmbeddingsModel,
            LocalSummaryModel,
            PreferLocalEmbeddings,
            PreferLocalSummary);
        UsageBudgets = new UsageBudgetConfiguration(
            DailyBudgetUsd,
            MonthlyBudgetUsd,
            maxRequestsPerDay,
            MaxDeepTasksPerDay,
            roleBudgetLimits);
        RateCard = usageRateCard ?? new UsageRateCard();
    }

    public string Model { get; }

    public IReadOnlyList<string> FallbackModels => _fallbackModels;

    public Uri OpenRouterEndpoint { get; }

    public string ApplicationName { get; }

    /// <summary>
    /// Stronger model reserved for an explicit planning workflow. <see cref="OpenRouter.OpenRouterChatClient"/>
    /// does not select it implicitly.
    /// </summary>
    public string PlanningModel { get; }

    public string AgentModel { get; }

    public string ReasoningModel { get; }

    public string? PremiumModel { get; }

    public string? EmbeddingsModel { get; }

    public string? LocalSummaryModel { get; }

    public bool PreferLocalEmbeddings { get; }

    public bool PreferLocalSummary { get; }

    public ModelPortfolio Portfolio { get; }

    /// <summary>
    /// User-configured global spending guardrails. Null means not configured. A
    /// <see cref="UsageLedger"/> evaluates them only when the host explicitly invokes its guard;
    /// the chat client never claims implicit enforcement.
    /// </summary>
    public decimal? DailyBudgetUsd { get; }

    public decimal? MonthlyBudgetUsd { get; }

    public int MaxDeepTasksPerDay { get; }

    public int? MaxRequestsPerDay => UsageBudgets.MaxRequestsPerDay;

    public UsageBudgetConfiguration UsageBudgets { get; }

    public UsageRateCard RateCard { get; }

    public bool HasConfiguredSpendingBudget => UsageBudgets.HasAnyFinancialLimit;

    public int MaxToolIterations { get; }

    public bool HasApiKey => _apiKey is not null;

    public bool IsLocalMode => !HasApiKey;

    internal string? GetApiKey() => _apiKey;

    /// <summary>Resolves only the lane explicitly selected by the caller.</summary>
    public string ResolveModel(ModelRole role)
    {
        var selection = Portfolio.Select(new ModelSelectionRequest(role));
        return selection.CanSendRemoteRequest
            ? selection.Model!
            : throw new InvalidOperationException(selection.Message);
    }

    public ModelSelection SelectModel(ModelSelectionRequest request) => Portfolio.Select(request);

    public static ViernesOptions FromEnvironment(Func<string, string?>? readVariable = null)
    {
        readVariable ??= Environment.GetEnvironmentVariable;
        var fallbacks = SplitModels(
            FirstConfigured(
                readVariable(FastFallbackModelsEnvironmentVariable),
                readVariable(FallbackModelsEnvironmentVariable)));
        var roleLimits = ReadRoleBudgetLimits(readVariable);

        return new ViernesOptions(
            readVariable(ApiKeyEnvironmentVariable),
            FirstConfigured(
                readVariable(FastModelEnvironmentVariable),
                readVariable(ModelEnvironmentVariable)),
            fallbacks.Length == 0 ? null : fallbacks,
            planningModel: readVariable(PlanningModelEnvironmentVariable),
            dailyBudgetUsd: ParseBudget(readVariable(DailyBudgetEnvironmentVariable), DailyBudgetEnvironmentVariable),
            monthlyBudgetUsd: ParseBudget(readVariable(MonthlyBudgetEnvironmentVariable), MonthlyBudgetEnvironmentVariable),
            maxDeepTasksPerDay: ParseDeepTaskLimit(readVariable(MaxDeepTasksEnvironmentVariable)),
            agentModel: readVariable(AgentModelEnvironmentVariable),
            reasoningModel: readVariable(ReasoningModelEnvironmentVariable),
            premiumModel: readVariable(PremiumModelEnvironmentVariable),
            embeddingsModel: readVariable(EmbeddingsModelEnvironmentVariable),
            localSummaryModel: readVariable(LocalSummaryModelEnvironmentVariable),
            preferLocalEmbeddings: ParseBoolean(
                readVariable(PreferLocalEmbeddingsEnvironmentVariable),
                PreferLocalEmbeddingsEnvironmentVariable,
                defaultValue: true),
            preferLocalSummary: ParseBoolean(
                readVariable(PreferLocalSummaryEnvironmentVariable),
                PreferLocalSummaryEnvironmentVariable,
                defaultValue: true),
            maxRequestsPerDay: ParseOptionalInt(
                readVariable(MaxRequestsEnvironmentVariable),
                MaxRequestsEnvironmentVariable),
            roleBudgetLimits: roleLimits,
            usageRateCard: UsageRateCard.ParseJson(readVariable(RateCardEnvironmentVariable)));
    }

    public static string GetRoleDailyBudgetEnvironmentVariable(ModelRole role) =>
        $"VIERNES_OPENROUTER_{RoleEnvironmentToken(role)}_DAILY_BUDGET_USD";

    public static string GetRoleMonthlyBudgetEnvironmentVariable(ModelRole role) =>
        $"VIERNES_OPENROUTER_{RoleEnvironmentToken(role)}_MONTHLY_BUDGET_USD";

    public static string GetRoleMaxRequestsEnvironmentVariable(ModelRole role) =>
        $"VIERNES_OPENROUTER_{RoleEnvironmentToken(role)}_MAX_REQUESTS_PER_DAY";

    /// <summary>Never includes the credential, making accidental structured logging safer.</summary>
    public override string ToString() =>
        $"ViernesOptions {{ Model = {Model}, FallbackModels = {string.Join(",", _fallbackModels)}, " +
        $"PlanningModel = {PlanningModel}, HasApiKey = {HasApiKey}, " +
        $"AgentModel = {AgentModel}, ReasoningModel = {ReasoningModel}, " +
        $"PremiumConfigured = {PremiumModel is not null}, " +
        $"DailyBudgetUsd = {DailyBudgetUsd?.ToString(CultureInfo.InvariantCulture) ?? "unset"}, " +
        $"MonthlyBudgetUsd = {MonthlyBudgetUsd?.ToString(CultureInfo.InvariantCulture) ?? "unset"}, " +
        $"MaxRequestsPerDay = {MaxRequestsPerDay?.ToString(CultureInfo.InvariantCulture) ?? "unset"}, " +
        $"MaxDeepTasksPerDay = {MaxDeepTasksPerDay}, " +
        $"OpenRouterEndpoint = {OpenRouterEndpoint} }}";

    private static string? NormalizeSecret(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static string? NormalizeModel(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static string? FirstConfigured(string? preferred, string? legacy) =>
        NormalizeModel(preferred) ?? NormalizeModel(legacy);

    private static IReadOnlyList<string> NormalizeFallbacks(IEnumerable<string>? models, string primaryModel) =>
        Array.AsReadOnly((models ?? DefaultFallbackModelsValue)
            .Select(NormalizeModel)
            .Where(model => model is not null && !string.Equals(model, primaryModel, StringComparison.OrdinalIgnoreCase))
            .Select(model => model!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(8)
            .ToArray());

    private static string[] SplitModels(string? models) =>
        string.IsNullOrWhiteSpace(models)
            ? Array.Empty<string>()
            : models.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);

    private static decimal? ParseBudget(string? value, string variableName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        if (!decimal.TryParse(
                value,
                NumberStyles.Number,
                CultureInfo.InvariantCulture,
                out var parsed))
        {
            throw new InvalidOperationException($"{variableName} must be a decimal value using '.' as separator.");
        }

        return ValidateBudget(parsed, variableName);
    }

    private static decimal? ValidateBudget(decimal? value, string parameterName)
    {
        if (value is < 0 or > 100_000)
        {
            throw new ArgumentOutOfRangeException(parameterName, "A budget must be between 0 and 100000 USD.");
        }

        return value;
    }

    private static int ParseDeepTaskLimit(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return 3;
        }

        if (!int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var parsed))
        {
            throw new InvalidOperationException($"{MaxDeepTasksEnvironmentVariable} must be an integer.");
        }

        return parsed;
    }

    private static int? ParseOptionalInt(string? value, string variableName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        if (!int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var parsed))
        {
            throw new InvalidOperationException($"{variableName} must be an integer.");
        }

        return RoleBudgetLimits.ValidateRequestLimit(parsed, variableName);
    }

    private static bool ParseBoolean(string? value, string variableName, bool defaultValue)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return defaultValue;
        }

        if (bool.TryParse(value, out var parsed))
        {
            return parsed;
        }

        var normalized = value.Trim().ToLowerInvariant();
        if (normalized is "1" or "yes" or "on")
        {
            return true;
        }

        if (normalized is "0" or "no" or "off")
        {
            return false;
        }

        throw new InvalidOperationException($"{variableName} must be true or false.");
    }

    private static IReadOnlyList<RoleBudgetLimits> ReadRoleBudgetLimits(Func<string, string?> readVariable)
    {
        ModelRole[] roles =
        [
            ModelRole.Fast,
            ModelRole.Agent,
            ModelRole.Reasoning,
            ModelRole.Premium,
            ModelRole.Embeddings,
            ModelRole.LocalSummary
        ];

        var limits = new List<RoleBudgetLimits>();
        foreach (var role in roles)
        {
            var dailyName = GetRoleDailyBudgetEnvironmentVariable(role);
            var monthlyName = GetRoleMonthlyBudgetEnvironmentVariable(role);
            var requestsName = GetRoleMaxRequestsEnvironmentVariable(role);
            var daily = ParseBudget(readVariable(dailyName), dailyName);
            var monthly = ParseBudget(readVariable(monthlyName), monthlyName);
            var maxRequests = ParseOptionalInt(readVariable(requestsName), requestsName);
            if (daily is not null || monthly is not null || maxRequests is not null)
            {
                limits.Add(new RoleBudgetLimits(role, daily, monthly, maxRequests));
            }
        }

        return limits;
    }

    private static string RoleEnvironmentToken(ModelRole role) =>
        RoleBudgetLimits.NormalizeRole(role) switch
        {
            ModelRole.Fast => "FAST",
            ModelRole.Agent => "AGENT",
            ModelRole.Reasoning => "REASONING",
            ModelRole.Premium => "PREMIUM",
            ModelRole.Embeddings => "EMBEDDINGS",
            ModelRole.LocalSummary => "LOCAL_SUMMARY",
            _ => throw new ArgumentOutOfRangeException(nameof(role))
        };

    private static Uri ValidateEndpoint(Uri endpoint)
    {
        if (!endpoint.IsAbsoluteUri)
        {
            throw new ArgumentException("The OpenRouter endpoint must be absolute.", nameof(endpoint));
        }

        // Production credentials must never travel over clear text. HTTP remains available only for
        // loopback test servers, which keeps the client independently testable.
        if (endpoint.Scheme != Uri.UriSchemeHttps &&
            !(endpoint.Scheme == Uri.UriSchemeHttp && endpoint.IsLoopback))
        {
            throw new ArgumentException("The OpenRouter endpoint must use HTTPS (or loopback HTTP for tests).", nameof(endpoint));
        }

        return endpoint;
    }
}
